image: sikalabs/ci

stages:
  - lint
  - build
  - deploy dev

variables:
  IMAGE: $CI_REGISTRY_IMAGE/app:$CI_COMMIT_REF_SLUG-$CI_COMMIT_SHORT_SHA-$CI_PIPELINE_ID
  GIT_CLEAN_FLAGS: -ffdx -e .yarn-cache

lint:
  stage: lint
  image: node:16
  except:
    variables:
      - $SKIP_STAGE_lint == "1" && $SKIP_BRANCH == $CI_COMMIT_REF_NAME
  script:
    - yarn --cache-folder .yarn-cache install
    - yarn lint


build:
  stage: build
  except:
    variables:
      - $SKIP_STAGE_build == "1" && $SKIP_BRANCH == $CI_COMMIT_REF_NAME
  script:
    - docker login $CI_REGISTRY -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD
    - docker build -t $IMAGE .
    - docker push $IMAGE

deploy dev:
  stage: deploy dev
  except:
    variables:
      - $SKIP_STAGE_deploy_dev == "1" && $SKIP_BRANCH == $CI_COMMIT_REF_NAME
  script:
    - helm repo add sikalabs https://helm.oxs.cz
    - helm upgrade --install proj-$CI_PROJECT_ID-$CI_COMMIT_REF_SLUG
      sikalabs/one-image
      --wait
      --timeout 60s
      --set image=$IMAGE
      --set host=$CI_PROJECT_PATH_SLUG-$CI_COMMIT_REF_SLUG.$KUBE_INGRESS_BASE_DOMAIN
  environment:
    name: dev/$CI_COMMIT_REF_SLUG
    url: https://$CI_PROJECT_PATH_SLUG-$CI_COMMIT_REF_SLUG.$KUBE_INGRESS_BASE_DOMAIN
    kubernetes:
      namespace: default
